name: test
on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macOS-latest', 'windows-latest']
        perl: ['5.30', '5.28', '5.10']
        exclude:
          # not supported on actions-setup-perl
          - os: windows-latest
            perl: '5.10'
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - run: cpanm --installdeps .
      - run: prove -lv t
